# Generated by Django 2.2.4 on 2019-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of pet', max_length=100)),
                ('breed', models.CharField(help_text='Breed of pet', max_length=100)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', help_text='Sex of pet', max_length=16)),
                ('birth_date', models.DateField(help_text='Birthday of pet')),
                ('vaccinated', models.BooleanField(help_text='Pet has been vaccinated')),
                ('profile_image', models.ImageField(help_text='Profile picture of pet', upload_to='')),
                ('bio', models.TextField(help_text='Biography of Pet')),
                ('adopt_me_if', models.TextField()),
                ('first_thing_people_notice_about_me', models.TextField()),
                ('friday_night', models.TextField()),
            ],
        ),
    ]
