# Generated by Django 2.2.4 on 2019-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopt_me_if',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='first_thing_people_notice_about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='friday_night',
            field=models.TextField(blank=True),
        ),
    ]
