# Generated by Django 3.0.7 on 2020-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_adoptrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptrequest',
            name='adopter',
            field=models.EmailField(help_text='Email of adopter', max_length=254),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile picture of pet', upload_to=''),
        ),
    ]
